export enum OrderStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum VendorStatus {
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  REJECTED = 'REJECTED',
}

export enum PaymentMethod {
  UPI = 'UPI',
  CREDIT_CARD = 'CREDIT_CARD',
  DEBIT_CARD = 'DEBIT_CARD',
  NET_BANKING = 'NET_BANKING',
  WALLETS = 'WALLETS',
  CASH_ON_DELIVERY = 'CASH_ON_DELIVERY',
}

export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  CATALOG_MANAGER = 'CATALOG_MANAGER',
  FINANCE_AUDITOR = 'FINANCE_AUDITOR',
  SUPPORT_ADMIN = 'SUPPORT_ADMIN',
}

export enum Currency {
  INR = 'INR',
  USD = 'USD',
  EUR = 'EUR',
}

export enum PayoutStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum AuditAction {
  VENDOR_APPROVE = 'VENDOR_APPROVE',
  VENDOR_REJECT = 'VENDOR_REJECT',
  PRODUCT_DELIST = 'PRODUCT_DELIST',
  COMMISSION_UPDATE = 'COMMISSION_UPDATE',
  SYSTEM_CONFIG = 'SYSTEM_CONFIG',
}

export enum MicroserviceStatus {
  HEALTHY = 'HEALTHY',
  DEGRADED = 'DEGRADED',
  DOWN = 'DOWN',
}
