export * from './Home';
export * from './Categories';
export * from './Search';
export * from './About';
export * from './Contact';
export * from './NotFound';
export { ProductListPage as Products } from '../features/products/pages/ProductListPage';
export { ProductDetailPage as ProductDetail } from '../features/products/pages/ProductDetailPage';
export { CartPage as Cart } from '../features/cart/pages/CartPage';
export { CheckoutPage as Checkout } from '../features/checkout/pages/CheckoutPage';
export { LoginPage as Login } from '../features/auth/pages/LoginPage';
export { RegisterPage as Register } from '../features/auth/pages/RegisterPage';
export { ForgotPasswordPage as ForgotPassword } from '../features/auth/pages/ForgotPasswordPage';
export { ResetPasswordPage as ResetPassword } from '../features/auth/pages/ResetPasswordPage';
export { ProfilePage as Profile } from '../features/profile/pages/ProfilePage';
export { AddressesPage as Addresses } from '../features/profile/pages/AddressesPage';
export { OrderHistoryPage as Orders } from '../features/orders/pages/OrderHistoryPage';
export { OrderDetailPage as OrderDetail } from '../features/orders/pages/OrderDetailPage';
export { WishlistPage as Wishlist } from '../features/wishlist/pages/WishlistPage';
export { NotificationsPage as Notifications } from '../features/notifications/pages/NotificationsPage';
export { SettingsPage as Settings } from '../features/settings/pages/SettingsPage';
